/** This file needs to be generated by HAMMOCK */
#include "gmock/gmock.h" 

/** Include the necessary header files (needed for types, constants, etc.) */
extern "C" {
#include "b.h"
} /* extern "C" */

/** One abstract class. For each undefined function create a virtual function within this class */
class WrapC {
 public:    
  virtual int some_number(int x) = 0;
};


/** One Mockup class. For each undefined function create the resp. MOCK_METHOD line */
class MockWrapC : public WrapC {
 public:
  MOCK_METHOD(int, some_number, (int x), (override));
};

extern MockWrapC wrapc;
