/** This file needs to be generated by HAMMOCK */
#include "b_mocks.h"

/** Create an object */
class_b_mocks b_mocks;

/** Foreach undefined function create the glue between c-function and the object method. */

