/** This file needs to be generated by HAMMOCK */
#ifndef b_mocks_h
#define b_mocks_h

#include "gmock/gmock.h" 

/** Include the necessary header files (needed for types, constants, etc.) */
extern "C" {
#include "a.h"
#include "c.h"
} /* extern "C" */

/** One abstract class. For each undefined function create a virtual function within this class */
class class_b {
 public:    

};


/** One Mockup class. For each undefined function create the resp. MOCK_METHOD line */
class class_b_mocks : public class_b {
 public:
};

extern class_b_mocks b_mocks;

#endif /* b_mocks_h */
