/** This file needs to be generated by HAMMOCK */
#include "c_mocks.h"

/** Create an object */
class_c_mocks c_mocks;

/** Foreach undefined function create the glue between c-function and the object method. */

