/** This file needs to be generated by HAMMOCK */
#include "c_mocks.h"

class_c_mocks *c_mocks_global_ptr = 0;

/** Foreach undefined function create the glue between c-function and the object method. */

