/** This file needs to be generated by HAMMOCK */
#ifndef c_mocks_h
#define c_mocks_h

#include "gmock/gmock.h" 

/** Include the necessary header files (needed for types, constants, etc.) */
extern "C" {
} /* extern "C" */

/** One Mockup class. For each undefined function create the resp. MOCK_METHOD line */
class class_c_mocks {
 public:
};

extern class_c_mocks *c_mocks_global_ptr;

#define CREATE_MOCK(name)   class_c_mocks name; c_mocks_global_ptr = &name;

#endif /* b_mocks_h */

